default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  # Change the usename and password to the postgres username and password that
  # you set during the installation of postgres.
  #
  # If you're on a Mac and installed postgres via homebrew, you can simply
  # leave the following two lines commented out.
  # username: postgres
  # password: 123456

development:
  <<: *default
  database: coder-pinterest_development

test:
  <<: *default
  database: coder-pinterest_test

production:
  url: <%= ENV['DATABASE_URL'] %>
